version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: astraion_db
      POSTGRES_USER: astraion_user
      POSTGRES_PASSWORD: astraion_pw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile   # Dockerfile is inside backend
    command: ["uvicorn", "astraion.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    ports:
      - "5173:5173"

volumes:
  postgres_data:
