# Generated by Django 5.2.5 on 2025-08-31 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("seats_count", models.PositiveIntegerField()),
                ("seat_map", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Bus Type",
                "verbose_name_plural": "Bus Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Chauffeur",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plate", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("active", models.BooleanField(default=True)),
                (
                    "bus_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buses",
                        to="fleet.bustype",
                    ),
                ),
            ],
            options={
                "ordering": ["plate"],
                "indexes": [
                    models.Index(
                        fields=["bus_type", "active"],
                        name="fleet_bus_bus_typ_f5162b_idx",
                    )
                ],
            },
        ),
    ]
