# Generated by Django 5.2.5 on 2025-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="e164",
            field=models.CharField(max_length=40),
        ),
    ]
