# Generated by Django 5.2.5 on 2025-08-31 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("time_hint", models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trip_date", models.DateField()),
                ("origin", models.CharField(max_length=120)),
                ("destination", models.CharField(max_length=120)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("return_time", models.TimeField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="fleet.bus",
                    ),
                ),
                (
                    "chauffeur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.chauffeur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripPickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_time", models.TimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "pickup_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trips.pickuppoint",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickups",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripSeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seat_no", models.PositiveIntegerField()),
                ("blocked", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["seat_no"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HOLD", "Hold"),
                            ("TENTATIVE", "Tentative"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="HOLD",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.client",
                    ),
                ),
                (
                    "trip_seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="trips.tripseat",
                    ),
                ),
            ],
            options={
                "ordering": ["trip_seat"],
            },
        ),
        migrations.AddIndex(
            model_name="tripseat",
            index=models.Index(
                fields=["trip", "seat_no"], name="trips_trips_trip_id_d1b100_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tripseat",
            unique_together={("trip", "seat_no")},
        ),
    ]
