# Generated by Django 5.2.5 on 2025-09-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="trip_seat",
        ),
    ]
